FROM arm64v8/ros:jazzy

SHELL ["/bin/bash", "-c"]

WORKDIR /app

RUN apt update && apt install -y \
    python3-gpiozero \
    ros-${ROS_DISTRO}-librealsense2* ros-${ROS_DISTRO}-realsense2-*

COPY . ros2_ws/
RUN cd ros2_ws && \
    source /opt/ros/jazzy/setup.bash && \
    colcon build

COPY ./docker_entrypoint.sh /

ENTRYPOINT ["/docker_entrypoint.sh"]
CMD ["bash"]
