FROM osrf/ros:jazzy-desktop

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY . ros2_ws/
RUN cd ros2_ws && \
    source /opt/ros/jazzy/setup.bash && \
    colcon build

COPY ./docker_entrypoint.sh /

ENTRYPOINT ["/docker_entrypoint.sh"]
CMD ["bash"]