FROM arm64v8/ros:jazzy

SHELL ["/bin/bash", "-c"]

WORKDIR /app

RUN apt update && apt install -y \
    libgpiod-dev gpiod python3-libgpiod \
    ros-${ROS_DISTRO}-librealsense2* ros-${ROS_DISTRO}-realsense2-*

COPY src /app/src

RUN colcon build

COPY ./docker_entrypoint.sh /

ENTRYPOINT ["/docker_entrypoint.sh"]
CMD ["bash"]
