FROM osrf/ros:jazzy-desktop-full

SHELL ["/bin/bash", "-c"]

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-rqt-image-view
    # rm -rf /var/lib/apt/lists/*

COPY . /app
RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
    colcon build --symlink-install

COPY ./docker_entrypoint.sh /

ENTRYPOINT ["/docker_entrypoint.sh"]
CMD ["bash"]