services:
  motors:
    container_name: robot-tank-rpi-motors
    image: robot-tank-rpi
    privileged: true
    network_mode: "host"
    environment:
      - ROS_STATIC_PEERS=10.1.1.6
    devices:
      - /dev/gpiochip1
    volumes:
      - /home/selexin/robot_rover/src:/app/src
      - /sys/class/gpio:/sys/class/gpio
      - /dev:/dev
      - /run/udev/:/run/udev/
    restart: unless-stopped
    command: ros2 launch rpi rpi.motors.launch.py

  encoder1:
    container_name: robot-tank-rpi-encoder-1
    image: robot-tank-rpi
    privileged: true
    network_mode: "host"
    environment:
      - ROS_STATIC_PEERS=10.1.1.6
    devices:
      - /dev/gpiochip1
    volumes:
      - /home/selexin/robot_rover/src:/app/src
      - /sys/class/gpio:/sys/class/gpio
      - /dev:/dev
      - /run/udev/:/run/udev/
    restart: unless-stopped
    command: ros2 launch rpi rpi.encoder1.launch.py
  
  encoder2:
    container_name: robot-tank-rpi-encoder-2
    image: robot-tank-rpi
    privileged: true
    network_mode: "host"
    environment:
      - ROS_STATIC_PEERS=10.1.1.6
    devices:
      - /dev/gpiochip1
    volumes:
      - /home/selexin/robot_rover/src:/app/src
      - /sys/class/gpio:/sys/class/gpio
      - /dev:/dev
      - /run/udev/:/run/udev/
    restart: unless-stopped
    command: ros2 launch rpi rpi.encoder2.launch.py
  

  lidar:
    container_name: robot-tank-rpi-lidar
    image: robot-tank-rpi
    privileged: true
    network_mode: "host"
    environment:
      - ROS_STATIC_PEERS=10.1.1.6
    devices:
      - /dev/serial0
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev:/dev
      - /run/udev/:/run/udev/
    restart: unless-stopped
    command: ros2 launch rpi rpi.lidar.launch.py

  robot_tank_desc:
    container_name: robot-tank-robot-desc
    image: robot-tank-rpi
    privileged: true
    network_mode: "host"
    environment:
      - ROS_STATIC_PEERS=10.1.1.6
    devices:
      - /dev/serial0
    volumes:
      - /home/selexin/robot_rover/src:/app/src
      - /sys/class/gpio:/sys/class/gpio
      - /dev:/dev
      - /run/udev/:/run/udev/
    restart: unless-stopped
    command: ros2 launch robot_tank_desc robot_nav.launch.py
  
  # cam1:
  #   container_name: robot-tank-rpi-cam-1
  #   image: robot-tank-rpi
  #   privileged: true
  #   network_mode: "host"
  #   environment:
  #     - ROS_STATIC_PEERS=10.1.1.6
  #   volumes:
  #     - /dev:/dev
  #     - /run/udev/:/run/udev/
  #   group_add:
  #     - video
  #   restart: unless-stopped
  #   command: ros2 launch rpi rpi.cam1.launch.py

  # cam2:
  #   container_name: robot-tank-rpi-cam-2
  #   image: robot-tank-rpi
  #   privileged: true
  #   network_mode: "host"
  #   environment:
  #     - ROS_STATIC_PEERS=10.1.1.6
  #   volumes:
  #     - /dev:/dev
  #     - /run/udev/:/run/udev/
  #   group_add:
  #     - video
  #   restart: unless-stopped
  #   command: ros2 launch rpi rpi.cam2.launch.py

  # cam1_servo:
  #   container_name: robot-tank-rpi-cam1-servo
  #   image: robot-tank-rpi
  #   privileged: true
  #   network_mode: "host"
  #   environment:
  #     - ROS_STATIC_PEERS=10.1.1.6
  #   devices:
  #     - /dev/gpiochip0
  #   volumes:
  #     - /sys/class/gpio:/sys/class/gpio
  #     - /dev:/dev
  #     - /run/udev/:/run/udev/
  #   restart: unless-stopped
  #   command: ros2 launch rpi rpi.cam1_servo.launch.py

  # cam2_servo:
  #   container_name: robot-tank-rpi-cam2-servo
  #   image: robot-tank-rpi
  #   privileged: true
  #   network_mode: "host"
  #   environment:
  #     - ROS_STATIC_PEERS=10.1.1.6
  #   devices:
  #     - /dev/gpiochip0
  #   volumes:
  #     - /sys/class/gpio:/sys/class/gpio
  #     - /dev:/dev
  #     - /run/udev/:/run/udev/
  #   restart: unless-stopped
  #   command: ros2 launch rpi rpi.cam2_servo.launch.py